1. Imports

In [1]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering as AggCls
from datetime import datetime
import numpy as np
from collections import Counter
import pandas as pd
import csv
from sklearn.cluster import KMeans
from transformers import BertTokenizer, BertModel
import torch
from sentence_transformers import SentenceTransformer, util

c:\Users\korey\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
bertErrorStories = []
bertCorrectStories = []

with open('./bertKmeansClusteringDistances.csv', mode='r', newline='', encoding='utf-8') as csv_file:
    
    thresholdAssign = 0

    csvReader = csv.reader(csv_file, delimiter=',') 

    withinTresholdCount = 0
    correctCount = 0
    incorrectCount = 0
    i = 0

    for row in csvReader:
        if i != 0:
            
            distanceMetricOne = float(row[2])
            distanceMetricTwo = float(row[4])
            correctEnding = int(row[5])

            if correctEnding == 1:
                if distanceMetricOne < distanceMetricTwo:
                    correctCount += 1
                    bertCorrectStories.append(row[0])
                else:
                    incorrectCount += 1
                    bertErrorStories.append(row[0])

            elif correctEnding == 2:
                if distanceMetricTwo < distanceMetricOne:
                    correctCount += 1
                    bertCorrectStories.append(row[0])
                else:
                    incorrectCount += 1
                    bertErrorStories.append(row[0])

        i = i + 1

In [3]:
print("BERT Model\nTotal Stories Processed: {}\nCount of Stories Classified Accurately: {}\nCount of Stories Classified Inaccurately: {}\nOverall Accuracy: {}%".format(correctCount + incorrectCount, correctCount, incorrectCount, (correctCount / (correctCount + incorrectCount) * 100)))

BERT Model
Total Stories Processed: 1571
Count of Stories Classified Accurately: 762
Count of Stories Classified Inaccurately: 809
Overall Accuracy: 48.504137492043284%

In [4]:
sbertErrorStories = []
sbertCorrectStories = []

with open('./sbertKmeansClusteringDistances.csv', mode='r', newline='', encoding='utf-8') as csv_file:
    
    thresholdAssign = 0

    csvReader = csv.reader(csv_file, delimiter=',') 

    #withinTresholdCount = 0
    correctCount = 0
    incorrectCount = 0
    i = 0

    for row in csvReader:
        if i != 0:
            
            distanceMetricOne = float(row[3])
            distanceMetricTwo = float(row[5])
            correctEnding = int(row[6])

          
            if correctEnding == 1:
                if distanceMetricOne < distanceMetricTwo:
                    correctCount += 1
                    sbertCorrectStories.append(row[0])
                else:
                    incorrectCount += 1
                    sbertErrorStories.append(row[0])

            elif correctEnding == 2:
                if distanceMetricTwo < distanceMetricOne:
                    correctCount += 1
                    sbertCorrectStories.append(row[0])
                else:
                    incorrectCount += 1
                    sbertErrorStories.append(row[0])

        i = i + 1

In [5]:
print("S-BERT Model\nTotal Stories Processed: {}\nCount of Stories Classified Accurately: {}\nCount of Stories Classified Inaccurately: {}\nOverall Accuracy: {}%".format(correctCount + incorrectCount, correctCount, incorrectCount, (correctCount / (correctCount + incorrectCount) * 100)))

S-BERT Model
Total Stories Processed: 1571
Count of Stories Classified Accurately: 964
Count of Stories Classified Inaccurately: 607
Overall Accuracy: 61.362189688096755%

In [6]:
CLOZE_DF = pd.read_csv("D://Python//MAForumProject//cloze_winter_2018_val.csv", sep = ",")
correctAnsList = list(CLOZE_DF['AnswerRightEnding'])
print(len(correctAnsList))

1571

In [7]:
s3bertCorrectStories = []
s3bertErrorStories = []

with open('./s3bertKmeansClusteringDistances.csv') as csv_file:
    
    
    csv_reader = csv.reader(csv_file, delimiter=',') 

    correct_count = 0
    incorrect_count = 0

    i = 0
    for row in csv_reader:
        if i:
            #print(i)
            if correctAnsList[i-1] == 1: #Note this value is subtracted by 1 since the correct_ans_list is a separate array declared elsewhere. The (i-1) factor accounts for the excelheader.
                if float(row[1]) < float(row[3]):
                    correct_count += 1
                    
                    for j, rows in CLOZE_DF.iterrows():
                        if str(row[0]) == str(rows['RandomFifthSentenceQuiz1']):
                            s3bertCorrectStories.append(rows['InputStoryid'])
                            #print(1)
                            break

                elif float(row[3]) < float(row[1]):
                    incorrect_count += 1

                    for j, rows in CLOZE_DF.iterrows():
                        if str(row[0]) == str(rows['RandomFifthSentenceQuiz1']):
                            s3bertErrorStories.append(rows['InputStoryid'])
                            #print(2)
                            break

            elif correctAnsList[i-1] == 2:

                if float(row[1]) < float(row[3]):
                    incorrect_count += 1

                    for j, rows in CLOZE_DF.iterrows():
                        if str(row[0]) == str(rows['RandomFifthSentenceQuiz1']):
                            s3bertErrorStories.append(rows['InputStoryid'])
                            #print(3)
                            break

                elif float(row[3]) < float(row[1]):
                    correct_count += 1

                    for j, rows in CLOZE_DF.iterrows():
                        if str(row[0]) == str(rows['RandomFifthSentenceQuiz1']):
                            s3bertCorrectStories.append(rows['InputStoryid'])
                            #print(4)
                            break
        
        i = i + 1

        if i % 100 == 0:
            print("{} Stories Processed With S3BERT".format(i))
    print("{} Stories Processed with S3BERT".format(i - 1))

100 Stories Processed With S3BERT
200 Stories Processed With S3BERT
300 Stories Processed With S3BERT
400 Stories Processed With S3BERT
500 Stories Processed With S3BERT
600 Stories Processed With S3BERT
700 Stories Processed With S3BERT
800 Stories Processed With S3BERT
900 Stories Processed With S3BERT
1000 Stories Processed With S3BERT
1100 Stories Processed With S3BERT
1200 Stories Processed With S3BERT
1300 Stories Processed With S3BERT
1400 Stories Processed With S3BERT
1500 Stories Processed With S3BERT
1571 Stories Processed with S3BERT

In [8]:
print("S3BERT Model\nTotal Stories Processed: {}\nCount of Stories Classified Accurately: {}\nCount of Stories Classified Inaccurately: {}\nOverall Accuracy: {}%".format(correct_count + incorrect_count, correct_count, incorrect_count, (correct_count / (correct_count + incorrect_count) * 100)))

S3BERT Model
Total Stories Processed: 1571
Count of Stories Classified Accurately: 1019
Count of Stories Classified Inaccurately: 552
Overall Accuracy: 64.8631444939529%

2. Error Analysis

2.1. Clustering Error Analysis

In [9]:
allThreeErrorList = []

bertS3bertErrorList = []

bertSbertErrorList = []

sbertS3bertErrorList = []

onlyS3bertErrorList = []

onlySBertErrorList = []

onlyBertErrorList= []


i = 0

for row in CLOZE_DF.iterrows():
    #print(row[1][0])
    #print(bertErrorStories)
    #print(row[1])
    if row[1]['InputStoryid'] in bertErrorStories and row[1]['InputStoryid'] in sbertErrorStories and row[1]['InputStoryid'] in s3bertErrorStories: #BERT, SBERT, and S3BERT Errors
        allThreeErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertErrorStories and row[1]['InputStoryid'] in sbertCorrectStories and row[1]['InputStoryid'] in s3bertErrorStories: #BERT & S3BERT Errors
        bertS3bertErrorList.append(row[1]['InputStoryid'])
        i+= 1
    elif row[1]['InputStoryid'] in bertCorrectStories and row[1]['InputStoryid'] in sbertErrorStories and row[1]['InputStoryid'] in s3bertErrorStories: #SBERT & S3BERT Errors
        sbertS3bertErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertErrorStories and row[1]['InputStoryid'] in sbertErrorStories and row[1]['InputStoryid'] in s3bertCorrectStories:
        bertSbertErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertCorrectStories and row[1]['InputStoryid'] in sbertCorrectStories and row[1]['InputStoryid'] in s3bertErrorStories: #S3BERT Errors
        onlyS3bertErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertErrorStories and row[1]['InputStoryid'] in sbertCorrectStories and row[1]['InputStoryid'] in s3bertCorrectStories: #BERT Errors
        onlyBertErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertCorrectStories and row[1]['InputStoryid'] in sbertErrorStories and row[1]['InputStoryid'] in s3bertCorrectStories: #SBERT Errors
        onlySBertErrorList.append(row[1]['InputStoryid'])
        i += 1
print(i)
print("All 3 Errors: {}\nBERT & S3BERT Errors: {}\nSBERT & S3BERT Errors: {}\nBERT & SBERT Errors: {}\nS3BERT Only Errors: {}\nBERT Only Errors: {}\nSBERT Only Errors: {}\nTotal Count of Error Stories: {}".format(len(allThreeErrorList), len(bertS3bertErrorList), len(sbertS3bertErrorList), len(bertSbertErrorList), len(onlyS3bertErrorList), len(onlyBertErrorList), len(onlySBertErrorList), len(allThreeErrorList) + len(bertS3bertErrorList) + len(sbertS3bertErrorList) + len(bertSbertErrorList) + len(onlyS3bertErrorList) + len(onlyBertErrorList) + len(onlySBertErrorList)))

1079
All 3 Errors: 302
BERT & S3BERT Errors: 31
SBERT & S3BERT Errors: 185
BERT & SBERT Errors: 69
S3BERT Only Errors: 34
BERT Only Errors: 407
SBERT Only Errors: 51
Total Count of Error Stories: 1079

2.2. Similarity Error Analysis

2.2.1. BERT Stories

In [10]:
bertEndingsDf = pd.read_csv('./bertSentBySentCosSims.csv')
bertEndingsDf.head(5)

,StoryID,First Ending Sent,S4E1CosSims,Second Ending Sent,S4E2CosSims,Correct Answer
0,138d5bfb-05cc-41e3-bf2c-fa85ebad14e2,He is happy now.,0.522551,He joined a gang.,0.472550,1
1,bff9f820-9605-4875-b9af-fe6f14d04256,The brownies are so delicious Laverne eats two...,0.685989,Laverne doesn't go to her friend's party.,0.693997,1
2,e8f628d5-9f97-40ed-8611-fc0e774673c4,Sarah then decided to move to Europe.,0.530687,Sarah decided that she preferred her home over...,0.691620,2
3,f5226bfe-9f26-4377-b05f-3d9568dbdec1,Gina liked the cookies so much she ate them al...,0.557086,Gina gave the cookies away at her church.,0.507014,1
4,69ac9b05-b956-402f-9fff-1f926ef9176b,I was very proud of my performance.,0.820335,I was very ashamed of my performance.,0.619275,1

In [11]:
bertSentbySentCorrectStories = []
bertSentbySentErrorStories = []

In [12]:
correctCount = 0
incorrectCount = 0
i = 0
for row in bertEndingsDf.iterrows():
        #print(row)
        # Skip empty rows or malformed lines
            
        correct_answer = int(row[1]['Correct Answer'])

        if correct_answer == 1:
            if float(row[1]['S4E1CosSims']) > float(row[1]['S4E2CosSims']):
                correctCount += 1
                bertSentbySentCorrectStories.append(row[1]['StoryID'])
            elif float(row[1]['S4E2CosSims']) > float(row[1]['S4E1CosSims']):
                incorrectCount += 1
                bertSentbySentErrorStories.append(row[1]['StoryID'])
        elif correct_answer == 2:
            if float(row[1]['S4E1CosSims']) > float(row[1]['S4E2CosSims']):
                incorrectCount += 1
                bertSentbySentErrorStories.append(row[1]['StoryID'])
            elif float(row[1]['S4E2CosSims']) > float(row[1]['S4E1CosSims']):
                correctCount += 1
                bertSentbySentCorrectStories.append(row[1]['StoryID'])

        i = i + 1

In [13]:
print(correctCount, incorrectCount, incorrectCount + correctCount)

778 793 1571

2.2.2. S-BERT Stories

In [14]:
sbertEndingsDf = pd.read_csv("./sbertSentBySentCosSims.csv")
sbertEndingsDf.head(5)

,storyID,S4E1 Similarities,S4E2 Similarities,Correct Ending
0,138d5bfb-05cc-41e3-bf2c-fa85ebad14e2,0.296945,0.336776,1
1,bff9f820-9605-4875-b9af-fe6f14d04256,0.842814,0.444635,1
2,e8f628d5-9f97-40ed-8611-fc0e774673c4,0.272204,0.368684,2
3,f5226bfe-9f26-4377-b05f-3d9568dbdec1,0.833238,0.709119,1
4,69ac9b05-b956-402f-9fff-1f926ef9176b,0.573658,0.486423,1

In [16]:
correctCount = 0
incorrectCount = 0

sbertSentbySentCorrectStories = []
sbertSentbySentErrorStories = []

clozeStoryIDs = list(CLOZE_DF["InputStoryid"])


for row in sbertEndingsDf.iterrows():
        #print(row)
        # Skip empty rows or malformed lines
            
    correct_answer = int(row[1]['Correct Ending'])

    if correct_answer == 1:
        if float(row[1]['S4E1 Similarities']) > float(row[1]['S4E2 Similarities']):
            correctCount += 1
            sbertSentbySentCorrectStories.append(row[1]['storyID'])
        elif float(row[1]['S4E2 Similarities']) > float(row[1]['S4E1 Similarities']):
            incorrectCount += 1
            sbertSentbySentErrorStories.append(row[1]['storyID'])
    elif correct_answer == 2:
        if float(row[1]['S4E1 Similarities']) > float(row[1]['S4E2 Similarities']):
            incorrectCount += 1
            sbertSentbySentErrorStories.append(row[1]['storyID'])
        elif float(row[1]['S4E2 Similarities']) > float(row[1]['S4E1 Similarities']):
            correctCount += 1
            sbertSentbySentCorrectStories.append(row[1]['storyID'])

    i = i + 1

In [17]:
print(correctCount, incorrectCount, incorrectCount + correctCount)
print(len(sbertSentbySentCorrectStories), len(sbertSentbySentErrorStories))

980 591 1571
980 591

2.2.4. S3BERT Stories

In [18]:
s3bertEndingsDf = pd.read_csv("./s3bertSentBySentCosSims.csv")
s3bertEndingsDf['Correct Ending'] = list(sbertEndingsDf['Correct Ending'])
s3bertEndingsDf.head(5)

,storyID,CosSimsS4E1,CosSimsS4E2,Correct Ending
0,138d5bfb-05cc-41e3-bf2c-fa85ebad14e2,0.297691,0.390822,1
1,bff9f820-9605-4875-b9af-fe6f14d04256,0.770141,0.398180,1
2,e8f628d5-9f97-40ed-8611-fc0e774673c4,0.277267,0.401914,2
3,f5226bfe-9f26-4377-b05f-3d9568dbdec1,0.718231,0.585659,1
4,69ac9b05-b956-402f-9fff-1f926ef9176b,0.590311,0.532475,1

In [20]:
correctCount = 0
incorrectCount = 0

s3bertSentbySentCorrectStories = []
s3bertSentbySentErrorStories = []

clozeStoryIDs = list(CLOZE_DF["InputStoryid"])


for row in s3bertEndingsDf.iterrows():
            
    correct_answer = int(row[1]['Correct Ending'])

    if correct_answer == 1:
        if float(row[1]['CosSimsS4E1']) > float(row[1]['CosSimsS4E2']):
            correctCount += 1
            s3bertSentbySentCorrectStories.append(row[1]['storyID'])
        elif float(row[1]['CosSimsS4E2']) > float(row[1]['CosSimsS4E1']):
            incorrectCount += 1
            s3bertSentbySentErrorStories.append(row[1]['storyID'])
    elif correct_answer == 2:
        if float(row[1]['CosSimsS4E1']) > float(row[1]['CosSimsS4E2']):
            incorrectCount += 1
            s3bertSentbySentErrorStories.append(row[1]['storyID'])
        elif float(row[1]['CosSimsS4E2']) > float(row[1]['CosSimsS4E1']):
            correctCount += 1
            s3bertSentbySentCorrectStories.append(row[1]['storyID'])

    i = i + 1

In [21]:
print(correctCount, incorrectCount, incorrectCount + correctCount)
print(len(s3bertSentbySentCorrectStories), len(s3bertSentbySentErrorStories))

1013 558 1571
1013 558

2.2.5. Similarity Errors

In [23]:
allThreeSentbySentErrorList = []

bertS3bertSentbySentErrorList = []

bertSbertSentbySentErrorList = []

sbertS3bertSentbySentErrorList = []

onlyS3bertSentbySentErrorList = []

onlySBertSentbySentErrorList = []

onlyBertSentbySentErrorList= []


i = 0

for row in CLOZE_DF.iterrows():
    #print(row[1][0])
    #print(bertErrorStories)
    if row[1]['InputStoryid'] in bertSentbySentErrorStories and row[1]['InputStoryid'] in sbertSentbySentErrorStories and row[1]['InputStoryid'] in s3bertSentbySentErrorStories: #BERT, SBERT, and S3BERT Errors
        allThreeSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertSentbySentErrorStories and row[1]['InputStoryid'] in sbertSentbySentCorrectStories and row[1]['InputStoryid'] in s3bertSentbySentErrorStories: #BERT & S3BERT Errors
        bertS3bertSentbySentErrorList.append(row[1]['InputStoryid'])
        i+= 1
    elif row[1]['InputStoryid'] in bertSentbySentCorrectStories and row[1]['InputStoryid'] in sbertSentbySentErrorStories and row[1]['InputStoryid'] in s3bertSentbySentErrorStories: #SBERT & S3BERT Errors
        sbertS3bertSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertSentbySentErrorStories and row[1]['InputStoryid'] in sbertSentbySentErrorStories and row[1]['InputStoryid'] in s3bertSentbySentCorrectStories:
        bertSbertSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertSentbySentCorrectStories and row[1]['InputStoryid'] in sbertSentbySentCorrectStories and row[1]['InputStoryid'] in s3bertSentbySentErrorStories: #S3BERT Errors
        onlyS3bertSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertSentbySentErrorStories and row[1]['InputStoryid'] in sbertSentbySentCorrectStories and row[1]['InputStoryid'] in s3bertSentbySentCorrectStories: #BERT Errors
        onlyBertSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
    elif row[1]['InputStoryid'] in bertSentbySentCorrectStories and row[1]['InputStoryid'] in sbertSentbySentErrorStories and row[1]['InputStoryid'] in s3bertSentbySentCorrectStories: #SBERT Errors
        onlySBertSentbySentErrorList.append(row[1]['InputStoryid'])
        i += 1
#print(i)
print("All 3 Errors: {}\nBERT & S3BERT Errors: {}\nSBERT & S3BERT Errors: {}\nBERT & SBERT Errors: {}\nS3BERT Only Errors: {}\nBERT Only Errors: {}\nSBERT Only Errors: {}\nTotal Count of Error Stories: {}".format(len(allThreeSentbySentErrorList), len(bertS3bertSentbySentErrorList), len(sbertS3bertSentbySentErrorList), len(bertSbertSentbySentErrorList), len(onlyS3bertSentbySentErrorList), len(onlyBertSentbySentErrorList), len(onlySBertSentbySentErrorList), len(allThreeSentbySentErrorList) + len(bertS3bertSentbySentErrorList) + len(sbertS3bertSentbySentErrorList) + len(bertSbertSentbySentErrorList) + len(onlyS3bertSentbySentErrorList) + len(onlyBertSentbySentErrorList) + len(onlySBertSentbySentErrorList)))

All 3 Errors: 294
BERT & S3BERT Errors: 37
SBERT & S3BERT Errors: 175
BERT & SBERT Errors: 76
S3BERT Only Errors: 52
BERT Only Errors: 386
SBERT Only Errors: 46
Total Count of Error Stories: 1066

3. Overlapping Error Stories Between Metrics

3.1. Both Metrics Overlapping S-BERT Unique

In [24]:
sbertOverlap = list(set(onlySBertErrorList) & set(onlySBertSentbySentErrorList))

print(len(sbertOverlap))

10

In [27]:
print(sbertOverlap)

['5080c261-9751-47c0-9cb9-7a9a326fb62f', '560de71d-f0e4-4430-b5b0-e6ceda4b9c20', 'a1ecda1c-7f69-4721-89ae-fb2e6ca9cb2f', '80b6447f-4c37-4194-9862-3785e5075463', '52dbbfda-5b42-4ace-8d59-55cee3eb30c0', '4a4ba70e-d51c-4574-b3f1-42675bef0059', '39c953ff-bb04-4997-a6be-3f4b07e0db56', 'bbc7c651-dd54-46ea-b057-7b001c105912', 'c55aad1c-4eb1-4c9c-a27a-5fbba9196f47', 'dfdf2b81-86fa-48f0-8a47-488ccf3e086b']

3.2. Both Metrics Overlapping S3BERT Unique

In [28]:
s3bertOverlap = list(set(onlyS3bertErrorList) & set(onlyS3bertSentbySentErrorList))

print(len(s3bertOverlap))

7

3.3. Both Metrics Overlapping BERT Unique

In [29]:
bertOverlap = list(set(onlyBertSentbySentErrorList) & set(onlyBertErrorList))

print(len(bertOverlap))

221

In [30]:
print(s3bertOverlap)

['8b3e5896-e1be-4ada-8e49-616acf0ec9b7', '285843c5-b7d9-4ae0-aa25-924a1b3b0dc9', '89cbffbf-4258-47a7-944a-9241ec0c2f17', '6e61a007-5fa7-4275-b45c-9a2d7a8ad2a8', 'dd098674-ee50-4033-a8b9-8637b80b34b6', '88340408-893a-4b3b-8401-c4f4935d2d70', '6b666c82-cfcd-4447-ba48-f91fcb27c170']

3.4. All Three Model Errors

In [31]:
allThreeOverlap = list(set(allThreeSentbySentErrorList) & set(allThreeErrorList))

print(len(allThreeOverlap))

147

In [32]:
print(allThreeOverlap)

['0a17cbf9-397b-4382-9ce0-0fd835626775', '6feb1097-ec20-4267-8428-5db886f7cdc4', '21a8fb15-2612-4fd0-9b10-675eb9473360', '19611623-a65a-4990-8803-559fdf276c3a', '6ab897f0-4f61-40f1-afa6-e9485e44316d', 'cca245f8-ea9f-4110-87c5-9b23b17ce789', '726a0fc9-8c6f-451e-838b-c48140817dfc', 'adaa9d18-572e-40f0-af81-c415abf793a4', '2029aa56-ef8f-4c6f-a599-6dae60566f01', 'dd3506fe-31ce-4bbb-9000-02c222da3466', '1ee70e30-2b21-45be-be71-379c84f910ea', '419d6f93-426a-458b-8e69-0a67e2e06ced', 'f9498236-c0d7-443e-85ea-3ded1a7c270e', '43aa020b-9bca-4af1-9ade-e281f41d04f0', '5af670c5-f7db-4f79-9407-054bb817fe93', '30e8e610-0fbb-4c86-b190-f4934736ab7d', '1a6f72b0-88e5-47b8-92d9-141200921477', 'dba303f0-ede3-4834-aad4-767eadafa744', '847fb1fc-aa6c-443c-98aa-fd4af3847c73', 'f3b25856-827a-42ba-8ca1-0426c1b01219', '23d95ddb-64bd-461e-b5e6-426a8b77c108', '80e87538-52cb-49b0-b0b6-b1caba694be4', '2ab4f4dc-7b16-45f5-8b72-99d8d10be148', '2e62070e-48c9-4aef-8a4c-f304065b9ad5', '72610204-f986-4e0a-ace9-3aff6625dd45', 'a7d985bc-8564-4262-8c45-6d211bd59f31', 'ca7ffb91-a043-4ab6-adcf-d43917f8e882', 'dad91d83-5774-4465-9256-0168882ff253', '5f02992e-3fc2-4e05-bb1f-a8e81400ff4d', '86991c22-02d9-4144-80e7-8531a7a5ccf4', 'bbdd62f2-63f7-48da-a4a9-cdb28f385037', '4010d4ae-e1f4-4348-8b20-91a774bf34ee', '03a810c5-6385-470a-bf0f-4beae08c5284', 'bb996fce-3cb3-4f2e-bf0e-f689ee6932f4', '851b28b1-31d3-4f81-9414-1760f328f07a', 'cd779b2b-1964-44a3-a00c-f1f51633dcac', 'ed448375-accb-4425-b7ed-e5af03f0d477', 'c8a83dec-8666-4241-8637-daf8c5e9c9fd', 'd96069af-cdd7-42d9-a4f2-1837b3b42d88', '1658b490-24a4-4f83-a42b-e6c679d0c2c2', '800c65e1-0a7d-4058-a943-a2f22efa1251', 'ea04f6ea-5b4f-4a24-a276-fe6c1e55667f', '06fb6922-d4c4-440c-9830-4ceccd1eacfc', 'a555794a-41f6-4893-9125-1a0a3a5445f1', 'a9ca9655-b64d-48c8-96dc-b14a9bc94890', '89eb34ec-56c2-4bf3-9e03-69b0c90a03d3', '5c227db5-f5db-47b6-a45c-d851bd811da1', '8e61c1c5-582f-4379-b332-dcb96faf3bf9', '5ccfaaba-fd87-4439-a947-a31fb8d943dd', '741833b1-bdf1-4be4-ba01-2a8ca81ae7be', '796cebdd-7d6f-4c1e-95c3-be941d0e4a55', '2e16fc90-126b-4d42-853d-adabc9329a04', '40f3b904-81c7-4e92-b245-ff20840733a2', '15f0716f-58ba-42c1-8551-969e4fed73b8', '6c3e9a76-0976-4597-b600-dcf6766d16fa', '8d81ed6f-9c29-468f-85f9-3ffe7a4d58b3', '6d0772be-9406-4257-af59-ab5f2e819e81', '8591a808-13de-487c-8468-0d49058b5ad3', 'ed5d6365-1862-4e67-8118-41630999a060', 'd46e5bd9-8a43-4670-b8c7-fe56f59cceae', '538e9d85-3ff1-483d-b8de-0c62348d225b', '2b7745a1-9e3a-402d-a806-1eebfb18ad5a', '7828385c-a209-4c05-81be-1916ca8d51c2', '7d177568-fd50-4c13-a5a5-929a12e765c5', 'bee259be-fcd9-4043-9047-0e199aaa8214', '10770264-1216-4bf9-a955-423d82dc6a92', 'e06719bc-6fdc-44b0-b40d-2892b339ba7b', '9409bd0a-fbdd-4450-8b41-5aac05fd5c36', '9f5c5186-d29d-4914-9be6-917ae7520f5e', '4cf8dc65-71e8-4664-9d71-c15cbd3d61ee', 'dac28c5f-fbd7-48dc-810e-c5126ac2ac89', '3541e6f4-8e10-473e-b8d0-2854f882e5e8', '65b3382b-23e1-41d4-b2cf-169da4f7d578', 'e92781bd-beee-4be6-ba37-0e2f7c258864', '732d31b0-0c2d-4ae0-a374-8592dc480df9', 'edb9e202-4c9e-4bb7-a18c-daa472a22092', '72e5dcdb-ae9f-4b0d-9734-059ad36c33b2', 'b929f263-1dcd-4a0b-b267-5d5ff2fe65bb', 'feb5f3a2-3e9b-466c-82b0-931fec45abc7', '5e0bf502-0e65-4d3d-bf92-ad19f8f5b5dd', 'e4086d5f-fa5a-41ee-a268-0c984a2cf816', '25561b53-b8fc-44ef-9d22-384325cdcf66', '7ae98915-03b0-40ae-9cd0-e1051e88c454', '131cc240-f6e0-4a76-81b8-aa6daf09e8f4', 'cbdf5369-ed2d-4534-9e68-7e1641969043', '25df4833-3565-45f6-a354-33c56e8dd8e7', 'b0d23a4d-9885-4428-87a5-aef0a58b8928', 'eeba73c7-ebe6-46d0-9dfe-939e794a90b7', '4b4eaf85-7b39-489e-a83e-9da41dd23f22', '0e92d1ba-0e2e-4052-99b7-d26a811da4b8', '293b2d9c-6aa5-4237-9d3a-e375bd92ae58', '5266d0a9-9676-4b0f-9947-5f0b9d2f5227', '0aedef28-e132-48d3-952d-60d6023e6354', '34505e75-67d3-47df-b140-429c87accabb', '46a10ff0-42c4-4136-9cfe-a12661232e2d', '6f96532b-9bc0-44d0-84fd-6bb7b99d69be', '4945b9f6-77ec-4bd0-b7c1-bbc093d07302', 'f11a5673-e26f-4e9c-9c5d-e0770601e357', 'c9e0ad92-16a3-4721-b221-bc7a7ea72195', '0d70ad27-5468-4aa8-b375-c0a273f73bab', 'e2a4744e-ed5a-4506-84dc-a2a4ad9912e9', '0505ab3d-b0a6-403b-83bd-1ff36755c0e5', '749b0981-388d-4deb-83d4-b4bc35b4a168', '32075b85-b08a-4503-ac1a-f8d92d2fa29f', '2f14cad7-8f3a-4a54-b7d8-206c515b780f', '8ae17467-e396-4f89-9d2a-eeade4539358', 'e4514b3b-2ac2-4e1f-8b23-6308185b3e25', '17701a43-538d-43de-8115-113ff7211818', '39a60eeb-95a3-481b-9e32-a9838d212c4e', '49bdca9c-4f31-4864-98bb-6db6e6e8d9ce', '73f5afd2-f1e4-420c-b536-ac86aed95ca5', '14791a39-5879-4cc8-91ef-ce366e93bdc6', 'a5d1a221-307a-4f9a-8ee1-dc235aad4b7d', 'ce62c6d1-55b5-47f2-bcbd-736598321ad5', 'e45e2974-a14f-4f8b-b681-ca7cb37cd2ee', '5a26b3c4-3d2e-4ffa-89f3-e7e3c7994a85', 'c6cdbb7f-ff5f-4b0b-9c41-6818d712dbcb', '6bf5185c-501a-449b-bc7b-c096f66c18d7', '7fb56f8e-afb9-4510-9abf-4be01e8a66f5', '0f1277f9-f7eb-4133-a067-8012ec4ce4c4', '217c5791-7a72-45d0-b3e8-1b4f20734f3a', '8683daa0-eb11-418c-b411-046283484c92', 'e2f74079-bcd6-485a-80c6-24be4fca4ae9', '81959648-7d1f-4f5e-a960-50465d1c6faf', '3ec93abb-d64a-45a9-bdc8-a8d366e1a999', '7be7b198-e925-4349-8f62-68e6fd50994a', 'e18c3d41-93e3-46b5-9e8e-3d9900f6b492', 'c545f1d9-8c13-4f15-907a-09d2115b1152', '3823e668-4a55-4c3d-a37a-544245f21eb5', '36b638c3-f2d1-44dc-bab1-5bf2a9d7fdff', '8ce7eaf0-bb21-4adf-9585-95484de98967', '2c99419a-7247-45cc-8f63-4d423e852f5d', '850f4d4d-0fb3-404a-9113-1197a4a3fe4a', 'a11cf506-7d19-4ab9-b0ac-a0fd85a9bd38', 'c71454d3-16c6-4852-bb0e-1149fd2b0e52', 'c284673c-f3fd-418d-8466-cdbef246fd3b', '4d567833-0f68-4976-bf8c-d10ba68e0956', '973e3d54-e7f2-4845-8460-d29f2baf3229', '2f595ff8-e86c-4de5-aa27-211501bc5a4d', '518faf54-80a9-4ab0-8019-4f9b76ac419b', 'dfadf8eb-0782-46f5-b8d6-f03b68044e5e', '4f062272-6c07-4f43-9e8b-ff12ba8dc264', '746bea88-d387-436e-afef-f5e92a2f8929', '27e6ed53-de20-4969-ac97-d1c767e66e8b', 'c5c1c868-cae5-4826-aae4-a8fb7eeca5a4', 'f3c5e059-72e7-412b-9248-80396c4e240a', 'a08e92e0-8aab-4f08-8bad-799b20d8b750']

3.5. BERT & S3BERT Model Errors

In [33]:
bertAnds3bertOverlap = list(set(bertS3bertSentbySentErrorList) & set(bertS3bertErrorList))

print(len(bertAnds3bertOverlap))

4